fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: App\Entity\Admin
    from_email:
        address: 'vasiljev.alexey@gmail.com'
        sender_name: 'Alexey Vasiljev'
